site_name: دليل المستخدم
site_description: RTL # set it to RTL for using RTL CSS

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: none
    navigation_depth: 3
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search:
        lang: ar

markdown_extensions:
  - footnotes

nav:
  - البحث‬: 'Searching.md'
  - المستعرض المدمج: 'Integrated-browser.md'
  - ⁧⁩الربط اللاحق⁧⁩: 'Postcoordination.md'
  - ملحوظة الترميز: 'Coding-note.md'
  - الفئات ذات الصلة في الفصل المعني بالأمهات: 'Related-categories-maternal-chapter.md'
  - الفئات المرتبطة بفصل الفترة المُحيطة بالوِلادَة: 'Related-categories-perinatal-chapter.md'