site_name: Guía del usuario 

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: none
    navigation_depth: 3
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search:
        lang: es

markdown_extensions:
  - footnotes

nav:
  - Búsqueda: 'Searching.md'
  - Navegador integrado: 'Integrated-browser.md'
  - Poscoordinación: 'Postcoordination.md'
  - Nota sobre la codificación: 'Coding-note.md'
  - Categorías relacionadas en el capítulo sobre causas maternas: 'Related-categories-maternal-chapter.md'
  - Categorías relacionadas en el capítulo de afecciones perinatales: 'Related-categories-perinatal-chapter.md'