site_name: Guide d'utilisation

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: none
    navigation_depth: 3
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search:
        lang: fr

markdown_extensions:
  - footnotes

nav:
  - Recherche: 'Searching.md'
  - Navigateur intégré: 'Integrated-browser.md'
  - Postcoordination: 'Postcoordination.md'
  - Note de codage: 'Coding-note.md'
  - Catégories connexes dans le chapitre maternité: 'Related-categories-maternal-chapter.md'
  - Catégories connexes dans le chapitre périnatal: 'Related-categories-perinatal-chapter.md'