site_name: Kullanıcı Kılavuzu

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: none
    navigation_depth: 3
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search:
        lang: tr

markdown_extensions:
  - footnotes

nav:
  - Aramalar: 'Searching.md'
  - Entegre tarayıcı: 'Integrated-browser.md'
  - Postkoordinasyon: 'Postcoordination.md'
  - Kodlama Notu: 'Coding-note.md'
  - Annelik bölümündeki ilgili kategoriler: 'Related-categories-maternal-chapter.md'
  - Perinatal bölümündeki ilgili kategoriler: 'Related-categories-perinatal-chapter.md'