site_name: Руководство пользователя

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: none
    navigation_depth: 3
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search:
        lang: ru

markdown_extensions:
  - footnotes

nav:
  - Поиск: 'Searching.md'
  - Встроенный браузер: 'Integrated-browser.md'
  - Посткоординация: 'Postcoordination.md'
  - Примечание к кодированию: 'Coding-note.md'
  - Связанные рубрики в классе о материнстве: 'Related-categories-maternal-chapter.md'
  - Связанные рубрики в перинатальном классе: 'Related-categories-perinatal-chapter.md'